# -*- coding: utf-8 -*-
"""NBclassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0OS8eOAWG2bTHbZYGSNxslDYGY7hok4
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

import io
data = pd.read_csv(io.BytesIO(uploaded['updated_dataset.csv']),encoding = "ISO-8859-1")
print(data.shape)
data.head()

data.dropna(axis=0)

from sklearn.model_selection import train_test_split
data = data.fillna(' ')
train_data , test_data = train_test_split(data,test_size=0.20)
train_data.head()

test_data.head()

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

text_clf = Pipeline([('vect', TfidfVectorizer()), 
                      ('clf', MultinomialNB()) ])

text_clf.fit(train_data['content'],train_data['sentiment'])

predicted = text_clf.predict(test_data['content'])

from sklearn import metrics
from sklearn.metrics import accuracy_score

print('Accuracy achieved is ' + str(np.mean(predicted == test_data['sentiment'])))
print(metrics.classification_report(test_data['sentiment'], predicted)),
metrics.confusion_matrix(test_data['sentiment'], predicted)

